converted apache to nginx

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,5 @@
-FROM php:7.2 as builder
+# build site dependencies from debian stretch php 7.3 image
+FROM php:7.3-stretch as builder
 
 ENV DART_SASS_VERSION 1.7.0
 
@@ -7,6 +8,7 @@ ARG GOOGLE_MAPS_API_KEY
 RUN apt-get update && apt-get install -y gnupg
 RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
 RUN apt-get update && apt-get install -y --no-install-recommends \
+        libzip-dev \
         build-essential \
         libfreetype6-dev \
         libjpeg62-turbo-dev \
@@ -15,11 +17,12 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
         mysql-client \
         git \
         nodejs \
-    && docker-php-ext-install gd \
-    && docker-php-ext-install opcache \
-    && docker-php-ext-install pdo \
-    && docker-php-ext-install pdo_mysql \
-    && docker-php-ext-install zip
+    && docker-php-ext-install \
+        gd \
+        opcache \
+        pdo \
+        pdo_mysql \
+        zip
 
 RUN rm -rf /var/lib/apt/lists/*
 
@@ -45,47 +48,139 @@ COPY composer.json /var/www/html/
 COPY composer.lock /var/www/html/
 RUN composer install --no-scripts --no-autoloader
 
-COPY web/themes/custom/move_mil/ /var/www/html/web/themes/custom/move_mil/
-COPY web/modules/custom/react_tools/ /var/www/html/web/modules/custom/react_tools/
+COPY move_mil/ /var/www/html/web/themes/custom/move_mil/
+COPY react_tools/ /var/www/html/web/modules/custom/react_tools/
 
 WORKDIR /var/www/html/web/themes/custom/move_mil/
-RUN npm install && npm run build
+RUN npm install
+RUN npm run build
 
 WORKDIR /var/www/html/web/modules/custom/react_tools/tools
 RUN npm install
 RUN npm run build
 
 COPY . /var/www/html
-COPY web/.htaccess /var/www/html/web
 
 WORKDIR /var/www/html
 
 RUN composer dump-autoload --optimize && \
         composer run-script post-install-cmd
 
-# Build our runtime image.
-FROM php:7.2-apache
+# build the server from debian stretch and nginx 1.16 stable
+FROM php:7.3-fpm-stretch
 
-ENV APACHE_DOCUMENT_ROOT /var/www/html/web
+# non root user to run the server after binding sockets as root
+ENV NGINX_DOC_ROOT /var/www/html/web
 ENV DRUPAL_CONSOLE_VERSION 1.8.0
 ENV DRUSH_VERSION 0.6.0
 
-WORKDIR /var/www/html
+ENV NGINX_VERSION   1.16.0
+ENV NJS_VERSION     0.3.1
+ENV PKG_RELEASE     1~stretch
 
-RUN apt-get update && apt-get install -y --no-install-recommends mysql-client libpng-dev\
+RUN set -x \
+	&& apt-get update \
+	&& apt-get install --no-install-recommends --no-install-suggests -y gnupg1 apt-transport-https ca-certificates \
+	&& \
+	NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+	found=''; \
+	for server in \
+		ha.pool.sks-keyservers.net \
+		hkp://keyserver.ubuntu.com:80 \
+		hkp://p80.pool.sks-keyservers.net:80 \
+		pgp.mit.edu \
+	; do \
+		echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+		apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+	done; \
+	test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+	apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
+	&& dpkgArch="$(dpkg --print-architecture)" \
+	&& nginxPackages=" \
+		nginx=${NGINX_VERSION}-${PKG_RELEASE} \
+		nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
+		nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
+		nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
+		nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-${PKG_RELEASE} \
+	" \
+	&& case "$dpkgArch" in \
+		amd64|i386) \
+# arches officialy built by upstream
+			echo "deb https://nginx.org/packages/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
+			&& apt-get update \
+			;; \
+		*) \
+# we're on an architecture upstream doesn't officially build for
+# let's build binaries from the published source packages
+			echo "deb-src https://nginx.org/packages/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
+			\
+# new directory for storing sources and .deb files
+			&& tempDir="$(mktemp -d)" \
+			&& chmod 777 "$tempDir" \
+# (777 to ensure APT's "_apt" user can access it too)
+			\
+# save list of currently-installed packages so build dependencies can be cleanly removed later
+			&& savedAptMark="$(apt-mark showmanual)" \
+			\
+# build .deb files from upstream's source packages (which are verified by apt-get)
+			&& apt-get update \
+			&& apt-get build-dep -y $nginxPackages \
+			&& ( \
+				cd "$tempDir" \
+				&& DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
+					apt-get source --compile $nginxPackages \
+			) \
+# we don't remove APT lists here because they get re-downloaded and removed later
+			\
+# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+# (which is done after we install the built packages so we don't have to redownload any overlapping dependencies)
+			&& apt-mark showmanual | xargs apt-mark auto > /dev/null \
+			&& { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
+			\
+# create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
+			&& ls -lAFh "$tempDir" \
+			&& ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
+			&& grep '^Package: ' "$tempDir/Packages" \
+			&& echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
+# work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
+#   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+#   ...
+#   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+			&& apt-get -o Acquire::GzipIndexes=false update \
+			;; \
+	esac \
+	\
+	&& apt-get install --no-install-recommends --no-install-suggests -y \
+						$nginxPackages \
+						gettext-base \
+	&& apt-get remove --purge --auto-remove -y apt-transport-https ca-certificates && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
+	\
+# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+	&& if [ -n "$tempDir" ]; then \
+		apt-get purge -y --auto-remove \
+		&& rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
+	fi
+
+# forward request and error logs to docker log collector
+RUN ln -sf /dev/stdout /var/log/nginx/access.log \
+	&& ln -sf /dev/stderr /var/log/nginx/error.log
+
+WORKDIR /var/www/html
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    mysql-client \
+    libpng-dev \
+    libzip-dev \
+    ca-certificates \
     && docker-php-ext-install gd \
-    && docker-php-ext-install opcache \
-    && docker-php-ext-install pdo \
-    && docker-php-ext-install pdo_mysql \
-    && docker-php-ext-install zip \
+    opcache \
+    pdo \
+    pdo_mysql \
+    zip \
     && rm -rf /var/lib/apt/lists/*
 
-COPY docker/php/php.ini /usr/local/etc/php
-COPY docker/apache/conf-enabled/ /etc/apache2/conf-enabled
+COPY php.ini /usr/local/etc/php
 
-RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
-RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
-RUN a2enmod rewrite
+COPY nginx.conf /etc/nginx/
 
 RUN curl https://github.com/hechoendrupal/drupal-console-launcher/releases/download/$DRUPAL_CONSOLE_VERSION/drupal.phar -L -o drupal.phar
 RUN mv drupal.phar /usr/local/bin/drupal
@@ -95,6 +190,16 @@ RUN curl https://github.com/drush-ops/drush-launcher/releases/download/$DRUSH_VE
 RUN mv drush.phar /usr/local/bin/drush
 RUN chmod +x /usr/local/bin/drush
 
+# copy in the files that the builder image built for drupal
 COPY --from=builder /var/www/html /var/www/html
 
+# make nginx able to access web root
+RUN chown -R www-data:www-data /var/www/html
+#start the php-fpm daemon to process php
+RUN php-fpm -D
+
 EXPOSE 80
+
+STOPSIGNAL SIGTERM
+
+CMD ["nginx", "-g", "daemon off;"]
